version: "3.4"

networks:
  default:

services:
  core: &src
    container_name: template-core
    environment:
      - DATABASE_NAME=${DATABASE_NAME}
      - DATABASE_USER=${DATABASE_USER}
      - DATABASE_PASSWORD=${DATABASE_PASSWORD}
      - DATABASE_HOST=${DATABASE_HOST}
      - DATABASE_PORT=${DATABASE_PORT}
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/opt/app
    networks:
      - default
    restart: unless-stopped
    ports:
      - "8000:8000"
