version: "3.4"

networks:
  default:

services:
  core: &src
    container_name: template-core
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./src:/opt/app
    networks:
      - default
    restart: unless-stopped
    ports:
      - "8000:8000"
